### Logar usuário
POST http://localhost:3333/session
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123123"
}

###
POST http://localhost:3333/schedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiQmFyYmVyIFBSTyIsImVtYWlsIjoidGVzdGVAdGVzdGUuY29tIiwic3ViIjoiNTQ0ZWZkNWUtYTllZC00ZmFhLWEyNGUtODZjODFiNjc1ODdkIiwiaWF0IjoxNzY2MTcyMzA5LCJleHAiOjE3Njg3NjQzMDl9.XXsyf9kFXIHpcc093fGTsB2EWI8USODDWvwEDg_T4-U

{
  "haircut_id": "ecfa558c-8e87-43e8-b4dc-07bca51e5e69",
  "customer": "Arthur"
}

###
GET http://localhost:3333/schedule
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiQmFyYmVyIFBSTyIsImVtYWlsIjoidGVzdGVAdGVzdGUuY29tIiwic3ViIjoiNTQ0ZWZkNWUtYTllZC00ZmFhLWEyNGUtODZjODFiNjc1ODdkIiwiaWF0IjoxNzY2MTcyMzA5LCJleHAiOjE3Njg3NjQzMDl9.XXsyf9kFXIHpcc093fGTsB2EWI8USODDWvwEDg_T4-U

###
DELETE http://localhost:3333/schedule?schedule_id=640052a6-fa35-4b0b-8c42-8ba1e2986bd2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiQmFyYmVyIFBSTyIsImVtYWlsIjoidGVzdGVAdGVzdGUuY29tIiwic3ViIjoiNTQ0ZWZkNWUtYTllZC00ZmFhLWEyNGUtODZjODFiNjc1ODdkIiwiaWF0IjoxNzY2MTcyMzA5LCJleHAiOjE3Njg3NjQzMDl9.XXsyf9kFXIHpcc093fGTsB2EWI8USODDWvwEDg_T4-U